version: '3'
services:
  dst_caves:
    container_name: dst_caves
    image: mathielo/dst-dedicated-server:0.3.1
    ports:
      - 10998:10998/udp
    networks:
      - dst_cluster
    links:
      - dst_master
    volumes:
      - ./DSTClusterConfig:/home/dst/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/home/dst/server_dst/mods
    environment:
      - SHARD_NAME=Caves

  dst_master:
    container_name: dst_master
    image: mathielo/dst-dedicated-server:0.3.1
    networks:
      - dst_cluster
    ports:
      - 10999:10999/udp
    volumes:
      - ./DSTClusterConfig:/home/dst/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/home/dst/server_dst/mods
    environment:
      - SHARD_NAME=Master

    # These allow to stdin when attaching to the container via `docker attach`
    # Any server commands should be sent to the master shard as it manages its slaves (Caves)
    stdin_open: true
    tty: true

networks:
  dst_cluster:

